name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set Environment Variables
        run: echo "TF_ENV_VARS=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} TF_VAR_aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} TF_VAR_aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} TF_VAR_aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV

      # 1. INIT
      - name: Terraform Init
        env: ${{ env.TF_ENV_VARS }}
        run: terraform init

      # 2. VALIDATE
      - name: Terraform Validate
        run: terraform validate
        
      # 3. PLAN (Destroy)
      - name: Terraform Plan (Destroy)
        env: ${{ env.TF_ENV_VARS }}
        run: terraform plan -destroy

      # 4. DESTROY
      - name: Terraform Destroy
        env: ${{ env.TF_ENV_VARS }}
        run: terraform destroy -auto-approve